package org.mesonet.models.site.forecast

import junit.framework.TestCase.*
import org.junit.Test
import org.mesonet.core.DefaultUnits

class ForecastModelParserTests
{
    @Test
    fun EmptyFileTest()
    {
        val parser = ForecastModelConverterFactory()

        val list = parser.Parse("")

        assertNotNull(list)
        assertEquals(list?.size, 0)
    }



    @Test
    fun BadFileTest()
    {
        val parser = ForecastModelConverterFactory()

        val list = parser.Parse("ERROR!!! ERROR!!! ERROR!!!")

        assertNotNull(list)
        assertEquals(list?.size, 0)
    }



    @Test
    fun InterruptedFileTest()
    {
        val parser = ForecastModelConverterFactory()

        val list = parser.Parse(
                "Today,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,85,S,S,20,21\n" +
                        "Tonight,http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg,Mostly Clear,Low,68,S,S,13,20\n" +
                        "Tomorrow,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,88,S,S,14,18\n" +
                        "ERROR!!!, ERROR!!!, ERROR!!!,\n" +
                        "Tomorrow Night,http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg,Mostly Cloudy,Low,68,S,S,9,16\n" +
                        "Monday,http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg,Slight Chance Thunderstorms,High,86,S,S,12,17\n" +
                        "Monday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg,Slight Chance Thunderstorms,Low,67,S,S,9,13\n" +
                        "Tuesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg,Chance Thunderstorms,High,87,S,S,7,9\n" +
                        "Tuesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra30.jpg,Chance Thunderstorms,Low,68,S,S,7,8\n" +
                        "Wednesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg,Chance Thunderstorms,High,84,SE,S,6,8\n" +
                        "Wednesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg,Chance Thunderstorms,Low,64,SE,SE,6,9\n")

        assertNotNull(list)
        assertEquals(list?.size, 10)
        assertNotNull(list[0])
        assertNotNull(list[0].GetTime())
        assertEquals(list[0].GetTime(), "Today")
        assertNotNull(list[0].GetIconId())
        assertEquals(list[0].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[0].GetStatus())
        assertEquals(list[0].GetStatus(), "Partly Sunny")
        assertNotNull(list[0].GetHighOrLow())
        assertEquals(list[0].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[0].GetTemp())
        assertEquals(list[0].GetTemp(), 85.0)
        assertNotNull(list[0].GetWindDirectionStart())
        assertEquals(list[0].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindDirectionEnd())
        assertEquals(list[0].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindMin())
        assertEquals(list[0].GetWindMin(), 20.0)
        assertNotNull(list[0].GetWindMax())
        assertEquals(list[0].GetWindMax(), 21.0)
        assertNotNull(list[1])
        assertNotNull(list[1].GetTime())
        assertEquals(list[1].GetTime(), "Tonight")
        assertNotNull(list[1].GetIconId())
        assertEquals(list[1].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg")
        assertNotNull(list[1].GetStatus())
        assertEquals(list[1].GetStatus(), "Mostly Clear")
        assertNotNull(list[1].GetHighOrLow())
        assertEquals(list[1].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[1].GetTemp())
        assertEquals(list[1].GetTemp(), 68.0)
        assertNotNull(list[1].GetWindDirectionStart())
        assertEquals(list[1].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindDirectionEnd())
        assertEquals(list[1].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindMin())
        assertEquals(list[1].GetWindMin(), 13.0)
        assertNotNull(list[1].GetWindMax())
        assertEquals(list[1].GetWindMax(), 20.0)
        assertNotNull(list[2])
        assertNotNull(list[2].GetTime())
        assertEquals(list[2].GetTime(), "Tomorrow")
        assertNotNull(list[2].GetIconId())
        assertEquals(list[2].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[2].GetStatus())
        assertEquals(list[2].GetStatus(), "Partly Sunny")
        assertNotNull(list[2].GetHighOrLow())
        assertEquals(list[2].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[2].GetTemp())
        assertEquals(list[2].GetTemp(), 88.0)
        assertNotNull(list[2].GetWindDirectionStart())
        assertEquals(list[2].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindDirectionEnd())
        assertEquals(list[2].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindMin())
        assertEquals(list[2].GetWindMin(), 14.0)
        assertNotNull(list[2].GetWindMax())
        assertEquals(list[2].GetWindMax(), 18.0)
        assertNotNull(list[3])
        assertNotNull(list[3].GetTime())
        assertEquals(list[3].GetTime(), "Tomorrow Night")
        assertNotNull(list[3].GetIconId())
        assertEquals(list[3].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg")
        assertNotNull(list[3].GetStatus())
        assertEquals(list[3].GetStatus(), "Mostly Cloudy")
        assertNotNull(list[3].GetHighOrLow())
        assertEquals(list[3].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[3].GetTemp())
        assertEquals(list[3].GetTemp(), 68.0)
        assertNotNull(list[3].GetWindDirectionStart())
        assertEquals(list[3].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindDirectionEnd())
        assertEquals(list[3].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindMin())
        assertEquals(list[3].GetWindMin(), 9.0)
        assertNotNull(list[3].GetWindMax())
        assertEquals(list[3].GetWindMax(), 16.0)
        assertNotNull(list[4])
        assertNotNull(list[4].GetTime())
        assertEquals(list[4].GetTime(), "Monday")
        assertNotNull(list[4].GetIconId())
        assertEquals(list[4].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg")
        assertNotNull(list[4].GetStatus())
        assertEquals(list[4].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[4].GetHighOrLow())
        assertEquals(list[4].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[4].GetTemp())
        assertEquals(list[4].GetTemp(), 86.0)
        assertNotNull(list[4].GetWindDirectionStart())
        assertEquals(list[4].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[4].GetWindDirectionEnd())
        assertEquals(list[4].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[4].GetWindMin())
        assertEquals(list[4].GetWindMin(), 12.0)
        assertNotNull(list[4].GetWindMax())
        assertEquals(list[4].GetWindMax(), 17.0)
        assertNotNull(list[5])
        assertNotNull(list[5].GetTime())
        assertEquals(list[5].GetTime(), "Monday Night")
        assertNotNull(list[5].GetIconId())
        assertEquals(list[5].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg")
        assertNotNull(list[5].GetStatus())
        assertEquals(list[5].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[5].GetHighOrLow())
        assertEquals(list[5].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[5].GetTemp())
        assertEquals(list[5].GetTemp(), 67.0)
        assertNotNull(list[5].GetWindDirectionStart())
        assertEquals(list[5].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[5].GetWindDirectionEnd())
        assertEquals(list[5].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[5].GetWindMin())
        assertEquals(list[5].GetWindMin(), 9.0)
        assertNotNull(list[5].GetWindMax())
        assertEquals(list[5].GetWindMax(), 13.0)
        assertNotNull(list[6])
        assertNotNull(list[6].GetTime())
        assertEquals(list[6].GetTime(), "Tuesday")
        assertNotNull(list[6].GetIconId())
        assertEquals(list[6].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg")
        assertNotNull(list[6].GetStatus())
        assertEquals(list[6].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[6].GetHighOrLow())
        assertEquals(list[6].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[6].GetTemp())
        assertEquals(list[6].GetTemp(), 87.0)
        assertNotNull(list[6].GetWindDirectionStart())
        assertEquals(list[6].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[6].GetWindDirectionEnd())
        assertEquals(list[6].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[6].GetWindMin())
        assertEquals(list[6].GetWindMin(), 7.0)
        assertNotNull(list[6].GetWindMax())
        assertEquals(list[6].GetWindMax(), 9.0)
        assertNotNull(list[7])
        assertNotNull(list[7].GetTime())
        assertEquals(list[7].GetTime(), "Tuesday Night")
        assertNotNull(list[7].GetIconId())
        assertEquals(list[7].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra30.jpg")
        assertNotNull(list[7].GetStatus())
        assertEquals(list[7].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[7].GetHighOrLow())
        assertEquals(list[7].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[7].GetTemp())
        assertEquals(list[7].GetTemp(), 68.0)
        assertNotNull(list[7].GetWindDirectionStart())
        assertEquals(list[7].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindDirectionEnd())
        assertEquals(list[7].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindMin())
        assertEquals(list[7].GetWindMin(), 7.0)
        assertNotNull(list[7].GetWindMax())
        assertEquals(list[7].GetWindMax(), 8.0)
        assertNotNull(list[8])
        assertNotNull(list[8].GetTime())
        assertEquals(list[8].GetTime(), "Wednesday")
        assertNotNull(list[8].GetIconId())
        assertEquals(list[8].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg")
        assertNotNull(list[8].GetStatus())
        assertEquals(list[8].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[8].GetHighOrLow())
        assertEquals(list[8].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[8].GetTemp())
        assertEquals(list[8].GetTemp(), 84.0)
        assertNotNull(list[8].GetWindDirectionStart())
        assertEquals(list[8].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[8].GetWindDirectionEnd())
        assertEquals(list[8].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[8].GetWindMin())
        assertEquals(list[8].GetWindMin(), 6.0)
        assertNotNull(list[8].GetWindMax())
        assertEquals(list[8].GetWindMax(), 8.0)
        assertNotNull(list[9])
        assertNotNull(list[9].GetTime())
        assertEquals(list[9].GetTime(), "Wednesday Night")
        assertNotNull(list[9].GetIconId())
        assertEquals(list[9].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg")
        assertNotNull(list[9].GetStatus())
        assertEquals(list[9].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[9].GetHighOrLow())
        assertEquals(list[9].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[9].GetTemp())
        assertEquals(list[9].GetTemp(), 64.0)
        assertNotNull(list[9].GetWindDirectionStart())
        assertEquals(list[9].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[9].GetWindDirectionEnd())
        assertEquals(list[9].GetWindDirectionEnd(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[9].GetWindMin())
        assertEquals(list[9].GetWindMin(), 6.0)
        assertNotNull(list[9].GetWindMax())
        assertEquals(list[9].GetWindMax(), 9.0)
    }




    @Test
    fun BadFormatTest()
    {
        val parser = ForecastModelConverterFactory()

        val list = parser.Parse(
                "Today,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,85,S,S,20,21\n" +
                        "Tonight,http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg,Mostly Clear,Low,68,S,S,13,20\n" +
                        "Tomorrow,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,88,S,S,14,18\n" +
                        "Tomorrow Night,http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg,Mostly Cloudy,bad format,bad format,S,S,9,16\n" +
                        "Monday,http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg,Slight Chance Thunderstorms,High,86,bad format,S,12,17\n" +
                        "Monday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg,Slight Chance Thunderstorms,Low,67,S,bad format,9,13\n" +
                        "Tuesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg,Chance Thunderstorms,High,87,S,S,bad format,9\n" +
                        "Tuesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra30.jpg,Chance Thunderstorms,Low,68,S,S,7,bad format\n" +
                        "Wednesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg,Chance Thunderstorms,High,84,SE,S,6,8\n" +
                        "Wednesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg,Chance Thunderstorms,Low,64,SE,SE,6,9\n")

        assertNotNull(list)
        assertEquals(list?.size, 10)
        assertNotNull(list[0])
        assertNotNull(list[0].GetTime())
        assertEquals(list[0].GetTime(), "Today")
        assertNotNull(list[0].GetIconId())
        assertEquals(list[0].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[0].GetStatus())
        assertEquals(list[0].GetStatus(), "Partly Sunny")
        assertNotNull(list[0].GetHighOrLow())
        assertEquals(list[0].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[0].GetTemp())
        assertEquals(list[0].GetTemp(), 85.0)
        assertNotNull(list[0].GetWindDirectionStart())
        assertEquals(list[0].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindDirectionEnd())
        assertEquals(list[0].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindMin())
        assertEquals(list[0].GetWindMin(), 20.0)
        assertNotNull(list[0].GetWindMax())
        assertEquals(list[0].GetWindMax(), 21.0)
        assertNotNull(list[1])
        assertNotNull(list[1].GetTime())
        assertEquals(list[1].GetTime(), "Tonight")
        assertNotNull(list[1].GetIconId())
        assertEquals(list[1].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg")
        assertNotNull(list[1].GetStatus())
        assertEquals(list[1].GetStatus(), "Mostly Clear")
        assertNotNull(list[1].GetHighOrLow())
        assertEquals(list[1].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[1].GetTemp())
        assertEquals(list[1].GetTemp(), 68.0)
        assertNotNull(list[1].GetWindDirectionStart())
        assertEquals(list[1].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindDirectionEnd())
        assertEquals(list[1].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindMin())
        assertEquals(list[1].GetWindMin(), 13.0)
        assertNotNull(list[1].GetWindMax())
        assertEquals(list[1].GetWindMax(), 20.0)
        assertNotNull(list[2])
        assertNotNull(list[2].GetTime())
        assertEquals(list[2].GetTime(), "Tomorrow")
        assertNotNull(list[2].GetIconId())
        assertEquals(list[2].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[2].GetStatus())
        assertEquals(list[2].GetStatus(), "Partly Sunny")
        assertNotNull(list[2].GetHighOrLow())
        assertEquals(list[2].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[2].GetTemp())
        assertEquals(list[2].GetTemp(), 88.0)
        assertNotNull(list[2].GetWindDirectionStart())
        assertEquals(list[2].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindDirectionEnd())
        assertEquals(list[2].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindMin())
        assertEquals(list[2].GetWindMin(), 14.0)
        assertNotNull(list[2].GetWindMax())
        assertEquals(list[2].GetWindMax(), 18.0)
        assertNotNull(list[3])
        assertNotNull(list[3].GetTime())
        assertEquals(list[3].GetTime(), "Tomorrow Night")
        assertNotNull(list[3].GetIconId())
        assertEquals(list[3].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg")
        assertNotNull(list[3].GetStatus())
        assertEquals(list[3].GetStatus(), "Mostly Cloudy")
        assertNull(list[3].GetHighOrLow())
        assertNull(list[3].GetTemp())
        assertNotNull(list[3].GetWindDirectionStart())
        assertEquals(list[3].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindDirectionEnd())
        assertEquals(list[3].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindMin())
        assertEquals(list[3].GetWindMin(), 9.0)
        assertNotNull(list[3].GetWindMax())
        assertEquals(list[3].GetWindMax(), 16.0)
        assertNotNull(list[4])
        assertNotNull(list[4].GetTime())
        assertEquals(list[4].GetTime(), "Monday")
        assertNotNull(list[4].GetIconId())
        assertEquals(list[4].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg")
        assertNotNull(list[4].GetStatus())
        assertEquals(list[4].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[4].GetHighOrLow())
        assertEquals(list[4].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[4].GetTemp())
        assertEquals(list[4].GetTemp(), 86.0)
        assertNull(list[4].GetWindDirectionStart())
        assertNotNull(list[4].GetWindDirectionEnd())
        assertEquals(list[4].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[4].GetWindMin())
        assertEquals(list[4].GetWindMin(), 12.0)
        assertNotNull(list[4].GetWindMax())
        assertEquals(list[4].GetWindMax(), 17.0)
        assertNotNull(list[5])
        assertNotNull(list[5].GetTime())
        assertEquals(list[5].GetTime(), "Monday Night")
        assertNotNull(list[5].GetIconId())
        assertEquals(list[5].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg")
        assertNotNull(list[5].GetStatus())
        assertEquals(list[5].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[5].GetHighOrLow())
        assertEquals(list[5].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[5].GetTemp())
        assertEquals(list[5].GetTemp(), 67.0)
        assertNotNull(list[5].GetWindDirectionStart())
        assertEquals(list[5].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNull(list[5].GetWindDirectionEnd())
        assertNotNull(list[5].GetWindMin())
        assertEquals(list[5].GetWindMin(), 9.0)
        assertNotNull(list[5].GetWindMax())
        assertEquals(list[5].GetWindMax(), 13.0)
        assertNotNull(list[6])
        assertNotNull(list[6].GetTime())
        assertEquals(list[6].GetTime(), "Tuesday")
        assertNotNull(list[6].GetIconId())
        assertEquals(list[6].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg")
        assertNotNull(list[6].GetStatus())
        assertEquals(list[6].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[6].GetHighOrLow())
        assertEquals(list[6].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[6].GetTemp())
        assertEquals(list[6].GetTemp(), 87.0)
        assertNotNull(list[6].GetWindDirectionStart())
        assertEquals(list[6].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[6].GetWindDirectionEnd())
        assertEquals(list[6].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNull(list[6].GetWindMin())
        assertNotNull(list[6].GetWindMax())
        assertEquals(list[6].GetWindMax(), 9.0)
        assertNotNull(list[7])
        assertNotNull(list[7].GetTime())
        assertEquals(list[7].GetTime(), "Tuesday Night")
        assertNotNull(list[7].GetIconId())
        assertEquals(list[7].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra30.jpg")
        assertNotNull(list[7].GetStatus())
        assertEquals(list[7].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[7].GetHighOrLow())
        assertEquals(list[7].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[7].GetTemp())
        assertEquals(list[7].GetTemp(), 68.0)
        assertNotNull(list[7].GetWindDirectionStart())
        assertEquals(list[7].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindDirectionEnd())
        assertEquals(list[7].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindMin())
        assertEquals(list[7].GetWindMin(), 7.0)
        assertNull(list[7].GetWindMax())
        assertNotNull(list[8])
        assertNotNull(list[8].GetTime())
        assertEquals(list[8].GetTime(), "Wednesday")
        assertNotNull(list[8].GetIconId())
        assertEquals(list[8].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg")
        assertNotNull(list[8].GetStatus())
        assertEquals(list[8].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[8].GetHighOrLow())
        assertEquals(list[8].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[8].GetTemp())
        assertEquals(list[8].GetTemp(), 84.0)
        assertNotNull(list[8].GetWindDirectionStart())
        assertEquals(list[8].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[8].GetWindDirectionEnd())
        assertEquals(list[8].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[8].GetWindMin())
        assertEquals(list[8].GetWindMin(), 6.0)
        assertNotNull(list[8].GetWindMax())
        assertEquals(list[8].GetWindMax(), 8.0)
        assertNotNull(list[9])
        assertNotNull(list[9].GetTime())
        assertEquals(list[9].GetTime(), "Wednesday Night")
        assertNotNull(list[9].GetIconId())
        assertEquals(list[9].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg")
        assertNotNull(list[9].GetStatus())
        assertEquals(list[9].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[9].GetHighOrLow())
        assertEquals(list[9].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[9].GetTemp())
        assertEquals(list[9].GetTemp(), 64.0)
        assertNotNull(list[9].GetWindDirectionStart())
        assertEquals(list[9].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[9].GetWindDirectionEnd())
        assertEquals(list[9].GetWindDirectionEnd(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[9].GetWindMin())
        assertEquals(list[9].GetWindMin(), 6.0)
        assertNotNull(list[9].GetWindMax())
        assertEquals(list[9].GetWindMax(), 9.0)
    }



    @Test
    fun MissingDataTest()
    {
        val parser = ForecastModelConverterFactory()

        val list = parser.Parse(
                ",http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,85,S,S,20,21\n" +
                        "Tonight,,Mostly Clear,Low,68,S,S,13,20\n" +
                        "Tomorrow,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,,High,88,S,S,14,18\n" +
                        "Tomorrow Night,http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg,Mostly Cloudy,,,S,S,9,16\n" +
                        "Monday,http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg,Slight Chance Thunderstorms,High,86,,S,12,17\n" +
                        "Monday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg,Slight Chance Thunderstorms,Low,67,S,,9,13\n" +
                        "Tuesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg,Chance Thunderstorms,High,87,S,S,,9\n" +
                        "Tuesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra30.jpg,Chance Thunderstorms,Low,68,S,S,7,\n" +
                        "Wednesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg,Chance Thunderstorms,High,84,SE,S,6,8\n" +
                        "Wednesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg,Chance Thunderstorms,Low,64,SE,SE,6,9\n")

        assertNotNull(list)
        assertEquals(list?.size, 10)
        assertNotNull(list[0])
        assertNotNull(list[0].GetTime())
        assertEquals(list[0].GetTime(), "")
        assertNotNull(list[0].GetIconId())
        assertEquals(list[0].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[0].GetStatus())
        assertEquals(list[0].GetStatus(), "Partly Sunny")
        assertNotNull(list[0].GetHighOrLow())
        assertEquals(list[0].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[0].GetTemp())
        assertEquals(list[0].GetTemp(), 85.0)
        assertNotNull(list[0].GetWindDirectionStart())
        assertEquals(list[0].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindDirectionEnd())
        assertEquals(list[0].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindMin())
        assertEquals(list[0].GetWindMin(), 20.0)
        assertNotNull(list[0].GetWindMax())
        assertEquals(list[0].GetWindMax(), 21.0)
        assertNotNull(list[1])
        assertNotNull(list[1].GetTime())
        assertEquals(list[1].GetTime(), "Tonight")
        assertNotNull(list[1].GetIconId())
        assertEquals(list[1].GetIconId(), "")
        assertNotNull(list[1].GetStatus())
        assertEquals(list[1].GetStatus(), "Mostly Clear")
        assertNotNull(list[1].GetHighOrLow())
        assertEquals(list[1].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[1].GetTemp())
        assertEquals(list[1].GetTemp(), 68.0)
        assertNotNull(list[1].GetWindDirectionStart())
        assertEquals(list[1].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindDirectionEnd())
        assertEquals(list[1].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindMin())
        assertEquals(list[1].GetWindMin(), 13.0)
        assertNotNull(list[1].GetWindMax())
        assertEquals(list[1].GetWindMax(), 20.0)
        assertNotNull(list[2])
        assertNotNull(list[2].GetTime())
        assertEquals(list[2].GetTime(), "Tomorrow")
        assertNotNull(list[2].GetIconId())
        assertEquals(list[2].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[2].GetStatus())
        assertEquals(list[2].GetStatus(), "")
        assertNotNull(list[2].GetHighOrLow())
        assertEquals(list[2].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[2].GetTemp())
        assertEquals(list[2].GetTemp(), 88.0)
        assertNotNull(list[2].GetWindDirectionStart())
        assertEquals(list[2].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindDirectionEnd())
        assertEquals(list[2].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindMin())
        assertEquals(list[2].GetWindMin(), 14.0)
        assertNotNull(list[2].GetWindMax())
        assertEquals(list[2].GetWindMax(), 18.0)
        assertNotNull(list[3])
        assertNotNull(list[3].GetTime())
        assertEquals(list[3].GetTime(), "Tomorrow Night")
        assertNotNull(list[3].GetIconId())
        assertEquals(list[3].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg")
        assertNotNull(list[3].GetStatus())
        assertEquals(list[3].GetStatus(), "Mostly Cloudy")
        assertNull(list[3].GetHighOrLow())
        assertNull(list[3].GetTemp())
        assertNotNull(list[3].GetWindDirectionStart())
        assertEquals(list[3].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindDirectionEnd())
        assertEquals(list[3].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindMin())
        assertEquals(list[3].GetWindMin(), 9.0)
        assertNotNull(list[3].GetWindMax())
        assertEquals(list[3].GetWindMax(), 16.0)
        assertNotNull(list[4])
        assertNotNull(list[4].GetTime())
        assertEquals(list[4].GetTime(), "Monday")
        assertNotNull(list[4].GetIconId())
        assertEquals(list[4].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg")
        assertNotNull(list[4].GetStatus())
        assertEquals(list[4].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[4].GetHighOrLow())
        assertEquals(list[4].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[4].GetTemp())
        assertEquals(list[4].GetTemp(), 86.0)
        assertNull(list[4].GetWindDirectionStart())
        assertNotNull(list[4].GetWindDirectionEnd())
        assertEquals(list[4].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[4].GetWindMin())
        assertEquals(list[4].GetWindMin(), 12.0)
        assertNotNull(list[4].GetWindMax())
        assertEquals(list[4].GetWindMax(), 17.0)
        assertNotNull(list[5])
        assertNotNull(list[5].GetTime())
        assertEquals(list[5].GetTime(), "Monday Night")
        assertNotNull(list[5].GetIconId())
        assertEquals(list[5].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg")
        assertNotNull(list[5].GetStatus())
        assertEquals(list[5].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[5].GetHighOrLow())
        assertEquals(list[5].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[5].GetTemp())
        assertEquals(list[5].GetTemp(), 67.0)
        assertNotNull(list[5].GetWindDirectionStart())
        assertEquals(list[5].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNull(list[5].GetWindDirectionEnd())
        assertNotNull(list[5].GetWindMin())
        assertEquals(list[5].GetWindMin(), 9.0)
        assertNotNull(list[5].GetWindMax())
        assertEquals(list[5].GetWindMax(), 13.0)
        assertNotNull(list[6])
        assertNotNull(list[6].GetTime())
        assertEquals(list[6].GetTime(), "Tuesday")
        assertNotNull(list[6].GetIconId())
        assertEquals(list[6].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg")
        assertNotNull(list[6].GetStatus())
        assertEquals(list[6].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[6].GetHighOrLow())
        assertEquals(list[6].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[6].GetTemp())
        assertEquals(list[6].GetTemp(), 87.0)
        assertNotNull(list[6].GetWindDirectionStart())
        assertEquals(list[6].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[6].GetWindDirectionEnd())
        assertEquals(list[6].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNull(list[6].GetWindMin())
        assertNotNull(list[6].GetWindMax())
        assertEquals(list[6].GetWindMax(), 9.0)
        assertNotNull(list[7])
        assertNotNull(list[7].GetTime())
        assertEquals(list[7].GetTime(), "Tuesday Night")
        assertNotNull(list[7].GetIconId())
        assertEquals(list[7].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra30.jpg")
        assertNotNull(list[7].GetStatus())
        assertEquals(list[7].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[7].GetHighOrLow())
        assertEquals(list[7].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[7].GetTemp())
        assertEquals(list[7].GetTemp(), 68.0)
        assertNotNull(list[7].GetWindDirectionStart())
        assertEquals(list[7].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindDirectionEnd())
        assertEquals(list[7].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindMin())
        assertEquals(list[7].GetWindMin(), 7.0)
        assertNull(list[7].GetWindMax())
        assertNotNull(list[8])
        assertNotNull(list[8].GetTime())
        assertEquals(list[8].GetTime(), "Wednesday")
        assertNotNull(list[8].GetIconId())
        assertEquals(list[8].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg")
        assertNotNull(list[8].GetStatus())
        assertEquals(list[8].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[8].GetHighOrLow())
        assertEquals(list[8].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[8].GetTemp())
        assertEquals(list[8].GetTemp(), 84.0)
        assertNotNull(list[8].GetWindDirectionStart())
        assertEquals(list[8].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[8].GetWindDirectionEnd())
        assertEquals(list[8].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[8].GetWindMin())
        assertEquals(list[8].GetWindMin(), 6.0)
        assertNotNull(list[8].GetWindMax())
        assertEquals(list[8].GetWindMax(), 8.0)
        assertNotNull(list[9])
        assertNotNull(list[9].GetTime())
        assertEquals(list[9].GetTime(), "Wednesday Night")
        assertNotNull(list[9].GetIconId())
        assertEquals(list[9].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg")
        assertNotNull(list[9].GetStatus())
        assertEquals(list[9].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[9].GetHighOrLow())
        assertEquals(list[9].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[9].GetTemp())
        assertEquals(list[9].GetTemp(), 64.0)
        assertNotNull(list[9].GetWindDirectionStart())
        assertEquals(list[9].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[9].GetWindDirectionEnd())
        assertEquals(list[9].GetWindDirectionEnd(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[9].GetWindMin())
        assertEquals(list[9].GetWindMin(), 6.0)
        assertNotNull(list[9].GetWindMax())
        assertEquals(list[9].GetWindMax(), 9.0)
    }



    @Test
    fun MissingDataSlotsTest()
    {
        val parser = ForecastModelConverterFactory()

        val list = parser.Parse(
                "Today,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,85,S,S,20,21\n" +
                        "Tonight,http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg,Mostly Clear,Low,68,S,S,13,20\n" +
                        "Tomorrow,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,88,S,S,14,18\n" +
                        "Tomorrow Night,http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg,Mostly Cloudy,Low,68,S,S,9,16\n" +
                        "Monday,http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg,Slight Chance Thunderstorms,High,86,S,S,12,17\n" +
                        "Monday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg,Slight Chance Thunderstorms,Low,67,S,S,9,13\n" +
                        "Tuesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg,Chance Thunderstorms,High,87,S,S,7,9\n" +
                        "Tuesday Night,Chance Thunderstorms,Low,68,S,7,8\n" +
                        "Wednesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg,Chance Thunderstorms,High,84,SE,S,6,8\n" +
                        "Wednesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg,Chance Thunderstorms,Low,64,SE,SE,6,9\n")

        assertNotNull(list)
        assertEquals(list?.size, 9)
        assertNotNull(list[0])
        assertNotNull(list[0].GetTime())
        assertEquals(list[0].GetTime(), "Today")
        assertNotNull(list[0].GetIconId())
        assertEquals(list[0].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[0].GetStatus())
        assertEquals(list[0].GetStatus(), "Partly Sunny")
        assertNotNull(list[0].GetHighOrLow())
        assertEquals(list[0].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[0].GetTemp())
        assertEquals(list[0].GetTemp(), 85.0)
        assertNotNull(list[0].GetWindDirectionStart())
        assertEquals(list[0].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindDirectionEnd())
        assertEquals(list[0].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindMin())
        assertEquals(list[0].GetWindMin(), 20.0)
        assertNotNull(list[0].GetWindMax())
        assertEquals(list[0].GetWindMax(), 21.0)
        assertNotNull(list[1])
        assertNotNull(list[1].GetTime())
        assertEquals(list[1].GetTime(), "Tonight")
        assertNotNull(list[1].GetIconId())
        assertEquals(list[1].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg")
        assertNotNull(list[1].GetStatus())
        assertEquals(list[1].GetStatus(), "Mostly Clear")
        assertNotNull(list[1].GetHighOrLow())
        assertEquals(list[1].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[1].GetTemp())
        assertEquals(list[1].GetTemp(), 68.0)
        assertNotNull(list[1].GetWindDirectionStart())
        assertEquals(list[1].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindDirectionEnd())
        assertEquals(list[1].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindMin())
        assertEquals(list[1].GetWindMin(), 13.0)
        assertNotNull(list[1].GetWindMax())
        assertEquals(list[1].GetWindMax(), 20.0)
        assertNotNull(list[2])
        assertNotNull(list[2].GetTime())
        assertEquals(list[2].GetTime(), "Tomorrow")
        assertNotNull(list[2].GetIconId())
        assertEquals(list[2].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[2].GetStatus())
        assertEquals(list[2].GetStatus(), "Partly Sunny")
        assertNotNull(list[2].GetHighOrLow())
        assertEquals(list[2].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[2].GetTemp())
        assertEquals(list[2].GetTemp(), 88.0)
        assertNotNull(list[2].GetWindDirectionStart())
        assertEquals(list[2].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindDirectionEnd())
        assertEquals(list[2].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindMin())
        assertEquals(list[2].GetWindMin(), 14.0)
        assertNotNull(list[2].GetWindMax())
        assertEquals(list[2].GetWindMax(), 18.0)
        assertNotNull(list[3])
        assertNotNull(list[3].GetTime())
        assertEquals(list[3].GetTime(), "Tomorrow Night")
        assertNotNull(list[3].GetIconId())
        assertEquals(list[3].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg")
        assertNotNull(list[3].GetStatus())
        assertEquals(list[3].GetStatus(), "Mostly Cloudy")
        assertNotNull(list[3].GetHighOrLow())
        assertEquals(list[3].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[3].GetTemp())
        assertEquals(list[3].GetTemp(), 68.0)
        assertNotNull(list[3].GetWindDirectionStart())
        assertEquals(list[3].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindDirectionEnd())
        assertEquals(list[3].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindMin())
        assertEquals(list[3].GetWindMin(), 9.0)
        assertNotNull(list[3].GetWindMax())
        assertEquals(list[3].GetWindMax(), 16.0)
        assertNotNull(list[4])
        assertNotNull(list[4].GetTime())
        assertEquals(list[4].GetTime(), "Monday")
        assertNotNull(list[4].GetIconId())
        assertEquals(list[4].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg")
        assertNotNull(list[4].GetStatus())
        assertEquals(list[4].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[4].GetHighOrLow())
        assertEquals(list[4].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[4].GetTemp())
        assertEquals(list[4].GetTemp(), 86.0)
        assertNotNull(list[4].GetWindDirectionStart())
        assertEquals(list[4].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[4].GetWindDirectionEnd())
        assertEquals(list[4].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[4].GetWindMin())
        assertEquals(list[4].GetWindMin(), 12.0)
        assertNotNull(list[4].GetWindMax())
        assertEquals(list[4].GetWindMax(), 17.0)
        assertNotNull(list[5])
        assertNotNull(list[5].GetTime())
        assertEquals(list[5].GetTime(), "Monday Night")
        assertNotNull(list[5].GetIconId())
        assertEquals(list[5].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg")
        assertNotNull(list[5].GetStatus())
        assertEquals(list[5].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[5].GetHighOrLow())
        assertEquals(list[5].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[5].GetTemp())
        assertEquals(list[5].GetTemp(), 67.0)
        assertNotNull(list[5].GetWindDirectionStart())
        assertEquals(list[5].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[5].GetWindDirectionEnd())
        assertEquals(list[5].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[5].GetWindMin())
        assertEquals(list[5].GetWindMin(), 9.0)
        assertNotNull(list[5].GetWindMax())
        assertEquals(list[5].GetWindMax(), 13.0)
        assertNotNull(list[6])
        assertNotNull(list[6].GetTime())
        assertEquals(list[6].GetTime(), "Tuesday")
        assertNotNull(list[6].GetIconId())
        assertEquals(list[6].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg")
        assertNotNull(list[6].GetStatus())
        assertEquals(list[6].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[6].GetHighOrLow())
        assertEquals(list[6].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[6].GetTemp())
        assertEquals(list[6].GetTemp(), 87.0)
        assertNotNull(list[6].GetWindDirectionStart())
        assertEquals(list[6].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[6].GetWindDirectionEnd())
        assertEquals(list[6].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[6].GetWindMin())
        assertEquals(list[6].GetWindMin(), 7.0)
        assertNotNull(list[6].GetWindMax())
        assertEquals(list[6].GetWindMax(), 9.0)
        assertNotNull(list[7])
        assertNotNull(list[7].GetTime())
        assertEquals(list[7].GetTime(), "Wednesday")
        assertNotNull(list[7].GetIconId())
        assertEquals(list[7].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg")
        assertNotNull(list[7].GetStatus())
        assertEquals(list[7].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[7].GetHighOrLow())
        assertEquals(list[7].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[7].GetTemp())
        assertEquals(list[7].GetTemp(), 84.0)
        assertNotNull(list[7].GetWindDirectionStart())
        assertEquals(list[7].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[7].GetWindDirectionEnd())
        assertEquals(list[7].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindMin())
        assertEquals(list[7].GetWindMin(), 6.0)
        assertNotNull(list[7].GetWindMax())
        assertEquals(list[7].GetWindMax(), 8.0)
        assertNotNull(list[8])
        assertNotNull(list[8].GetTime())
        assertEquals(list[8].GetTime(), "Wednesday Night")
        assertNotNull(list[8].GetIconId())
        assertEquals(list[8].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg")
        assertNotNull(list[8].GetStatus())
        assertEquals(list[8].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[8].GetHighOrLow())
        assertEquals(list[8].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[8].GetTemp())
        assertEquals(list[8].GetTemp(), 64.0)
        assertNotNull(list[8].GetWindDirectionStart())
        assertEquals(list[8].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[8].GetWindDirectionEnd())
        assertEquals(list[8].GetWindDirectionEnd(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[8].GetWindMin())
        assertEquals(list[8].GetWindMin(), 6.0)
        assertNotNull(list[8].GetWindMax())
        assertEquals(list[8].GetWindMax(), 9.0)
    }


    @Test
    fun GoodFileTest()
    {
        val parser = ForecastModelConverterFactory()

        val list = parser.Parse(
                "Today,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,85,S,S,20,21\n" +
                "Tonight,http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg,Mostly Clear,Low,68,S,S,13,20\n" +
                "Tomorrow,http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg,Partly Sunny,High,88,S,S,14,18\n" +
                "Tomorrow Night,http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg,Mostly Cloudy,Low,68,S,S,9,16\n" +
                "Monday,http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg,Slight Chance Thunderstorms,High,86,S,S,12,17\n" +
                "Monday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg,Slight Chance Thunderstorms,Low,67,S,S,9,13\n" +
                "Tuesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg,Chance Thunderstorms,High,87,S,S,7,9\n" +
                "Tuesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra30.jpg,Chance Thunderstorms,Low,68,S,S,7,8\n" +
                "Wednesday,http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg,Chance Thunderstorms,High,84,SE,S,6,8\n" +
                "Wednesday Night,http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg,Chance Thunderstorms,Low,64,SE,SE,6,9\n")

        assertNotNull(list)
        assertEquals(list?.size, 10)
        assertNotNull(list[0])
        assertNotNull(list[0].GetTime())
        assertEquals(list[0].GetTime(), "Today")
        assertNotNull(list[0].GetIconId())
        assertEquals(list[0].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[0].GetStatus())
        assertEquals(list[0].GetStatus(), "Partly Sunny")
        assertNotNull(list[0].GetHighOrLow())
        assertEquals(list[0].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[0].GetTemp())
        assertEquals(list[0].GetTemp(), 85.0)
        assertNotNull(list[0].GetWindDirectionStart())
        assertEquals(list[0].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindDirectionEnd())
        assertEquals(list[0].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[0].GetWindMin())
        assertEquals(list[0].GetWindMin(), 20.0)
        assertNotNull(list[0].GetWindMax())
        assertEquals(list[0].GetWindMax(), 21.0)
        assertNotNull(list[1])
        assertNotNull(list[1].GetTime())
        assertEquals(list[1].GetTime(), "Tonight")
        assertNotNull(list[1].GetIconId())
        assertEquals(list[1].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg")
        assertNotNull(list[1].GetStatus())
        assertEquals(list[1].GetStatus(), "Mostly Clear")
        assertNotNull(list[1].GetHighOrLow())
        assertEquals(list[1].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[1].GetTemp())
        assertEquals(list[1].GetTemp(), 68.0)
        assertNotNull(list[1].GetWindDirectionStart())
        assertEquals(list[1].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindDirectionEnd())
        assertEquals(list[1].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[1].GetWindMin())
        assertEquals(list[1].GetWindMin(), 13.0)
        assertNotNull(list[1].GetWindMax())
        assertEquals(list[1].GetWindMax(), 20.0)
        assertNotNull(list[2])
        assertNotNull(list[2].GetTime())
        assertEquals(list[2].GetTime(), "Tomorrow")
        assertNotNull(list[2].GetIconId())
        assertEquals(list[2].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/sct.jpg")
        assertNotNull(list[2].GetStatus())
        assertEquals(list[2].GetStatus(), "Partly Sunny")
        assertNotNull(list[2].GetHighOrLow())
        assertEquals(list[2].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[2].GetTemp())
        assertEquals(list[2].GetTemp(), 88.0)
        assertNotNull(list[2].GetWindDirectionStart())
        assertEquals(list[2].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindDirectionEnd())
        assertEquals(list[2].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[2].GetWindMin())
        assertEquals(list[2].GetWindMin(), 14.0)
        assertNotNull(list[2].GetWindMax())
        assertEquals(list[2].GetWindMax(), 18.0)
        assertNotNull(list[3])
        assertNotNull(list[3].GetTime())
        assertEquals(list[3].GetTime(), "Tomorrow Night")
        assertNotNull(list[3].GetIconId())
        assertEquals(list[3].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/nbkn.jpg")
        assertNotNull(list[3].GetStatus())
        assertEquals(list[3].GetStatus(), "Mostly Cloudy")
        assertNotNull(list[3].GetHighOrLow())
        assertEquals(list[3].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[3].GetTemp())
        assertEquals(list[3].GetTemp(), 68.0)
        assertNotNull(list[3].GetWindDirectionStart())
        assertEquals(list[3].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindDirectionEnd())
        assertEquals(list[3].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[3].GetWindMin())
        assertEquals(list[3].GetWindMin(), 9.0)
        assertNotNull(list[3].GetWindMax())
        assertEquals(list[3].GetWindMax(), 16.0)
        assertNotNull(list[4])
        assertNotNull(list[4].GetTime())
        assertEquals(list[4].GetTime(), "Monday")
        assertNotNull(list[4].GetIconId())
        assertEquals(list[4].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra20.jpg")
        assertNotNull(list[4].GetStatus())
        assertEquals(list[4].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[4].GetHighOrLow())
        assertEquals(list[4].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[4].GetTemp())
        assertEquals(list[4].GetTemp(), 86.0)
        assertNotNull(list[4].GetWindDirectionStart())
        assertEquals(list[4].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[4].GetWindDirectionEnd())
        assertEquals(list[4].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[4].GetWindMin())
        assertEquals(list[4].GetWindMin(), 12.0)
        assertNotNull(list[4].GetWindMax())
        assertEquals(list[4].GetWindMax(), 17.0)
        assertNotNull(list[5])
        assertNotNull(list[5].GetTime())
        assertEquals(list[5].GetTime(), "Monday Night")
        assertNotNull(list[5].GetIconId())
        assertEquals(list[5].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra20.jpg")
        assertNotNull(list[5].GetStatus())
        assertEquals(list[5].GetStatus(), "Slight Chance Thunderstorms")
        assertNotNull(list[5].GetHighOrLow())
        assertEquals(list[5].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[5].GetTemp())
        assertEquals(list[5].GetTemp(), 67.0)
        assertNotNull(list[5].GetWindDirectionStart())
        assertEquals(list[5].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[5].GetWindDirectionEnd())
        assertEquals(list[5].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[5].GetWindMin())
        assertEquals(list[5].GetWindMin(), 9.0)
        assertNotNull(list[5].GetWindMax())
        assertEquals(list[5].GetWindMax(), 13.0)
        assertNotNull(list[6])
        assertNotNull(list[6].GetTime())
        assertEquals(list[6].GetTime(), "Tuesday")
        assertNotNull(list[6].GetIconId())
        assertEquals(list[6].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra30.jpg")
        assertNotNull(list[6].GetStatus())
        assertEquals(list[6].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[6].GetHighOrLow())
        assertEquals(list[6].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[6].GetTemp())
        assertEquals(list[6].GetTemp(), 87.0)
        assertNotNull(list[6].GetWindDirectionStart())
        assertEquals(list[6].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[6].GetWindDirectionEnd())
        assertEquals(list[6].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[6].GetWindMin())
        assertEquals(list[6].GetWindMin(), 7.0)
        assertNotNull(list[6].GetWindMax())
        assertEquals(list[6].GetWindMax(), 9.0)
        assertNotNull(list[7])
        assertNotNull(list[7].GetTime())
        assertEquals(list[7].GetTime(), "Tuesday Night")
        assertNotNull(list[7].GetIconId())
        assertEquals(list[7].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra30.jpg")
        assertNotNull(list[7].GetStatus())
        assertEquals(list[7].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[7].GetHighOrLow())
        assertEquals(list[7].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[7].GetTemp())
        assertEquals(list[7].GetTemp(), 68.0)
        assertNotNull(list[7].GetWindDirectionStart())
        assertEquals(list[7].GetWindDirectionStart(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindDirectionEnd())
        assertEquals(list[7].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[7].GetWindMin())
        assertEquals(list[7].GetWindMin(), 7.0)
        assertNotNull(list[7].GetWindMax())
        assertEquals(list[7].GetWindMax(), 8.0)
        assertNotNull(list[8])
        assertNotNull(list[8].GetTime())
        assertEquals(list[8].GetTime(), "Wednesday")
        assertNotNull(list[8].GetIconId())
        assertEquals(list[8].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/tsra40.jpg")
        assertNotNull(list[8].GetStatus())
        assertEquals(list[8].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[8].GetHighOrLow())
        assertEquals(list[8].GetHighOrLow(), Forecast.HighOrLow.High)
        assertNotNull(list[8].GetTemp())
        assertEquals(list[8].GetTemp(), 84.0)
        assertNotNull(list[8].GetWindDirectionStart())
        assertEquals(list[8].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[8].GetWindDirectionEnd())
        assertEquals(list[8].GetWindDirectionEnd(), DefaultUnits.CompassDirections.S)
        assertNotNull(list[8].GetWindMin())
        assertEquals(list[8].GetWindMin(), 6.0)
        assertNotNull(list[8].GetWindMax())
        assertEquals(list[8].GetWindMax(), 8.0)
        assertNotNull(list[9])
        assertNotNull(list[9].GetTime())
        assertEquals(list[9].GetTime(), "Wednesday Night")
        assertNotNull(list[9].GetIconId())
        assertEquals(list[9].GetIconId(), "http://www.nws.noaa.gov/weather/images/fcicons/ntsra40.jpg")
        assertNotNull(list[9].GetStatus())
        assertEquals(list[9].GetStatus(), "Chance Thunderstorms")
        assertNotNull(list[9].GetHighOrLow())
        assertEquals(list[9].GetHighOrLow(), Forecast.HighOrLow.Low)
        assertNotNull(list[9].GetTemp())
        assertEquals(list[9].GetTemp(), 64.0)
        assertNotNull(list[9].GetWindDirectionStart())
        assertEquals(list[9].GetWindDirectionStart(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[9].GetWindDirectionEnd())
        assertEquals(list[9].GetWindDirectionEnd(), DefaultUnits.CompassDirections.SE)
        assertNotNull(list[9].GetWindMin())
        assertEquals(list[9].GetWindMin(), 6.0)
        assertNotNull(list[9].GetWindMax())
        assertEquals(list[9].GetWindMax(), 9.0)
    }
}